export const skills = {
  theObvious: [
    'HTML',
    'CSS',
    'SCSS',
    'JavaScript',
    'TypeScript',
    'git',
    'npm / yarn',
    'Rest APIs / JSON',
    'React Hooks',
    'fetch / axios',
  ],
  librariesFrameworks: [
    'React 18',
    'NextJS 14',
    'TailwindCSS',
    'MaterialUI',
    'Ant Design',
    'Redux Toolkit',
    'Zustand',
    'React Query',
    'Google Maps Api',
    'Yandex Maps Api',
    'Socket.io',
    'I18N',
  ],
  toolsOfTheTrade: ['Github', 'Notion', 'Trello'],
};
