export const skills = {
  theObvious: [
    'HTML',
    'CSS',
    'SCSS',
    'JavaScript',
    'TypeScript',
    'git',
    'npm / yarn',
    'Rest APIs / JSON',
    'React Hooks',
    'fetch / axios',
  ],
  librariesFrameworks: [
    'React 18',
    'NextJS 14',
    'Tailwind',
    'MaterialUI',
    'Ant Design',
    'Redux Toolkit',
    'Zustand',
    'React Query',
  ],
  toolsOfTheTrade: ['Github', 'Notion'],
};
